[package]
name = "metalog-ingestion"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
metalog-types = { workspace = true }
metalog-db = { workspace = true }
metalog-metastore = { workspace = true }
metalog-schema = { workspace = true }
metalog-proto = { workspace = true }
metalog-timeutil = { workspace = true }
metalog-logutil = { workspace = true }
serde_json = { workspace = true }
mysql_async = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
