FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests -Dexec.skip=true

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /build/target/clp-service-*.jar /app/clp-service.jar
