package com.yscope.clp.service.metastore.model;

import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Represents an aggregation task to consolidate multiple IR files into an archive.
 *
 * <p>Tasks are generated by the coordinator's policy engine and executed by workers (in this POC,
 * executed inline by the coordinator).
 */
public class ConsolidationTask {
  private final String taskId;
  private String archivePath; // Mutable: set by Planner with instance ID
  private final List<String> irFilePaths;
  private final String applicationId;
  private final long createdAt;

  // Task execution metadata
  private TaskStatus status;
  private long submittedAt; // When added to submitted queue
  private long processingStartedAt; // When worker claimed task
  private long completedAt; // When task finished
  private long estimatedArchiveSizeBytes;
  private long actualArchiveSizeBytes;
  private String workerId; // Worker executing this task
  private String errorMessage;

  // Coordinator instance tracking (for stale completion detection)
  private String instanceId; // Coordinator instance that created this task

  // Kafka source tracking (for offset watermark)
  // Represents the maximum source offset of all IR files in this task.
  // Once this task completes, offsets up to this value are safe to commit.
  private long sourceOffset = -1L; // -1 indicates not set

  public enum TaskStatus {
    SUBMITTED,
    PROCESSING,
    COMPLETED,
    FAILED
  }

  public ConsolidationTask(String archivePath, List<String> irFilePaths, String applicationId) {
    this.taskId = UUID.randomUUID().toString();
    this.archivePath = archivePath;
    this.irFilePaths = List.copyOf(irFilePaths); // Immutable copy
    this.applicationId = applicationId;
    this.createdAt = System.currentTimeMillis();
    this.status = TaskStatus.SUBMITTED;
  }

  // Getters
  public String getTaskId() {
    return taskId;
  }

  public String getArchivePath() {
    return archivePath;
  }

  /**
   * Set the archive path.
   *
   * <p>Called by Planner to set the path including coordinator instance ID for crash recovery
   * support.
   *
   * @param archivePath The archive path including instance ID
   */
  public void setArchivePath(String archivePath) {
    this.archivePath = archivePath;
  }

  public List<String> getIrFilePaths() {
    return irFilePaths;
  }

  public String getApplicationId() {
    return applicationId;
  }

  public long getCreatedAt() {
    return createdAt;
  }

  public TaskStatus getStatus() {
    return status;
  }

  public void setStatus(TaskStatus status) {
    this.status = status;
  }

  public long getSubmittedAt() {
    return submittedAt;
  }

  public void setSubmittedAt(long submittedAt) {
    this.submittedAt = submittedAt;
  }

  public long getProcessingStartedAt() {
    return processingStartedAt;
  }

  public void setProcessingStartedAt(long processingStartedAt) {
    this.processingStartedAt = processingStartedAt;
  }

  public String getWorkerId() {
    return workerId;
  }

  public void setWorkerId(String workerId) {
    this.workerId = workerId;
  }

  public long getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(long completedAt) {
    this.completedAt = completedAt;
  }

  public long getEstimatedArchiveSizeBytes() {
    return estimatedArchiveSizeBytes;
  }

  public void setEstimatedArchiveSizeBytes(long estimatedArchiveSizeBytes) {
    this.estimatedArchiveSizeBytes = estimatedArchiveSizeBytes;
  }

  public long getActualArchiveSizeBytes() {
    return actualArchiveSizeBytes;
  }

  public void setActualArchiveSizeBytes(long actualArchiveSizeBytes) {
    this.actualArchiveSizeBytes = actualArchiveSizeBytes;
  }

  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  /**
   * Get the Kafka source offset for this task. This is the maximum offset of all IR files included
   * in this task.
   *
   * @return The Kafka offset, or -1 if not set
   */
  public long getSourceOffset() {
    return sourceOffset;
  }

  /**
   * Set the Kafka source offset for this task. Should be set to the maximum offset of all IR files
   * in this task.
   *
   * @param sourceOffset The Kafka offset
   */
  public void setSourceOffset(long sourceOffset) {
    this.sourceOffset = sourceOffset;
  }

  /**
   * Check if this task has a valid source offset.
   *
   * @return true if sourceOffset is set (>= 0)
   */
  public boolean hasSourceOffset() {
    return sourceOffset >= 0;
  }

  /**
   * Get the coordinator instance ID that created this task.
   *
   * <p>Used for stale completion detection. If a completion arrives from a different coordinator
   * instance, it should be rejected and the archive deleted.
   *
   * @return The coordinator instance ID
   */
  public String getInstanceId() {
    return instanceId;
  }

  /**
   * Set the coordinator instance ID.
   *
   * @param instanceId The coordinator instance ID
   */
  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  // Utility methods

  /** Calculate total IR size from the list of files. */
  public long getTotalIrSizeBytes() {
    // In POC, we don't have actual sizes, so estimate based on file count
    // Real implementation would sum actual file sizes
    return irFilePaths.size() * 1024L * 1024; // 1MB per file estimate
  }

  /** Get the number of IR files in this task. */
  public int getFileCount() {
    return irFilePaths.size();
  }

  /** Mark task as started (worker claimed). */
  public void markStarted() {
    this.status = TaskStatus.PROCESSING;
    this.processingStartedAt = System.currentTimeMillis();
  }

  /** Mark task as completed successfully. */
  public void markCompleted(long archiveSizeBytes) {
    this.status = TaskStatus.COMPLETED;
    this.completedAt = System.currentTimeMillis();
    this.actualArchiveSizeBytes = archiveSizeBytes;
  }

  /** Mark task as failed. */
  public void markFailed(String errorMessage) {
    this.status = TaskStatus.FAILED;
    this.completedAt = System.currentTimeMillis();
    this.errorMessage = errorMessage;
  }

  /**
   * Get task execution duration in milliseconds. Measures time from when worker claimed task to
   * completion.
   */
  public long getDurationMs() {
    if (processingStartedAt == 0) {
      return 0;
    }
    if (completedAt == 0) {
      return System.currentTimeMillis() - processingStartedAt;
    }
    return completedAt - processingStartedAt;
  }

  /** Get total time in system (submitted to completed). */
  public long getTotalLatencyMs() {
    if (submittedAt == 0) {
      return 0;
    }
    long endTime = (completedAt == 0) ? System.currentTimeMillis() : completedAt;
    return endTime - submittedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    ConsolidationTask that = (ConsolidationTask) o;
    return Objects.equals(taskId, that.taskId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId);
  }

  @Override
  public String toString() {
    return String.format(
        "ConsolidationTask{id=%s, app=%s, files=%d, status=%s, archive=%s, offset=%d, instance=%s}",
        taskId, applicationId, irFilePaths.size(), status, archivePath, sourceOffset, instanceId);
  }
}
