package com.yscope.clp.service.coordinator.workflow.consolidation;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Objects;
import java.util.UUID;

/**
 * Generates unique archive object keys that include the coordinator instance ID.
 *
 * <p>Archive object key format:
 *
 * <pre>
 * {table}/{date}/{instanceId}/{taskId}.clp
 * </pre>
 *
 * <p>The bucket is not part of the object key — it is stored separately in the {@link
 * com.yscope.clp.service.metastore.model.TaskPayload TaskPayload}.
 *
 * <p>Including the instance ID in the path ensures:
 *
 * <ol>
 *   <li>Archives from different coordinator instances never collide
 *   <li>Safe to delete archives from crashed instances without affecting current data
 * </ol>
 *
 * <p>Example paths:
 *
 * <pre>
 * spark/2024/01/15/abc123-uuid/task-001.clp
 * spark/2024/01/15/abc123-uuid/task-002.clp
 * </pre>
 */
public class ArchivePathGenerator {
  private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy/MM/dd");
  private static final ZoneId UTC = ZoneId.of("UTC");

  private final String table;
  private final String instanceId;

  /**
   * Create an archive path generator.
   *
   * @param table The metadata table name (used as path prefix)
   * @param instanceId The coordinator instance ID
   */
  public ArchivePathGenerator(String table, String instanceId) {
    this.table = Objects.requireNonNull(table, "table is required");
    this.instanceId = Objects.requireNonNull(instanceId, "instanceId is required");
  }

  /**
   * Generate a unique archive object key.
   *
   * @param taskId The task ID (used as filename)
   * @return Object key (without bucket)
   */
  public String generate(String taskId) {
    return generate(taskId, Instant.now());
  }

  /**
   * Generate a unique archive object key with a specific timestamp.
   *
   * @param taskId The task ID (used as filename)
   * @param timestamp The timestamp for date partitioning
   * @return Object key (without bucket)
   */
  public String generate(String taskId, Instant timestamp) {
    LocalDate date = timestamp.atZone(UTC).toLocalDate();
    String datePath = date.format(DATE_FORMAT);

    return String.format("%s/%s/%s/%s.clp", table, datePath, instanceId, taskId);
  }

  /**
   * Generate a unique archive object key with a random task ID.
   *
   * @return Object key (without bucket)
   */
  public String generateWithRandomId() {
    return generate(UUID.randomUUID().toString());
  }

  /**
   * Extract the instance ID from an archive path.
   *
   * @param archivePath The archive path (object key without bucket)
   * @return The instance ID, or null if not parseable
   */
  public static String extractInstanceId(String archivePath) {
    if (archivePath == null || archivePath.isEmpty()) {
      return null;
    }
    // Path format: table/yyyy/MM/dd/instanceId/taskId.clp
    String[] parts = archivePath.split("/");
    if (parts.length >= 6) {
      // instanceId is the second-to-last part
      return parts[parts.length - 2];
    }
    return null;
  }

  /**
   * Check if an archive path was generated by a specific instance.
   *
   * @param archivePath The archive path (object key without bucket)
   * @param instanceId The instance ID to check
   * @return true if the path was generated by this instance
   */
  public static boolean isFromInstance(String archivePath, String instanceId) {
    String pathInstanceId = extractInstanceId(archivePath);
    return instanceId.equals(pathInstanceId);
  }

  public String getTable() {
    return table;
  }

  public String getInstanceId() {
    return instanceId;
  }
}
