database:
  host: db
  port: 3306
  database: metalog_metadata
  user: root
  password: password
  poolSize: 10
  poolMinIdle: 2

server:
  grpc:
    enabled: true
    port: 9091
  health:
    enabled: true
    port: 8081

coordinator:
  nodeIdEnvVar: HOSTNAME

worker:
  concurrency: 0

tables:
  - name: clp_cockroachdb
